services:
  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: patientDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=patientDB --username=postgres --port=5432" ]
      interval: 5s
      timeout: 5s
      retries: 10