services:
  app:
    image: patient-demo:latest
    container_name: patient-demo
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresDB:5432/patientDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgresDB:
        condition: service_healthy
    ports:
      - '8181:8181'

  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: patientDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=patientDB --username=postgres --port=5432" ]
      interval: 5s
      timeout: 5s
      retries: 10