spring:
  datasource:
    url: ENVIRONMENT
    username: ENVIRONMENT
    password: ENVIRONMENT

  web:
    locale: en_US
    locale-resolver: fixed

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml

server:
  port: 8181

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /